fs = require('fs')
path = require('path')

componentPath = basePath = path.resolve('.').split('.meteor')[0]+'imports/components'

apiPath = ''

dirTree = (filename) ->
  stats = fs.lstatSync(filename)
  info =
    path: filename
    name: path.basename(filename)
  if stats.isDirectory()
    info.type = 'folder'
    info.children = fs.readdirSync(filename).map((child) ->
      dirTree filename + '/' + child
    )
  else
    # Assuming it's a file. In real life it could be a symlink or
    # something else!
    info.type = 'file'
  info

if module.parent == undefined
  # node dirTree.js ~/foo/bar
  util = require('util')
  console.log util.inspect(dirTree(process.argv[2]), false, null)

info = dirTree componentPath
console.log info
# ---
# generated by js2coffee 2.2.0

# TODO: 先从当前目录里面找对应的组件，再从上级目录查找，再从上级目录的所有子目录查找，从而导入这个组件
# TODO: 当系统是server的时候，每次运行时，自动将所有的目录内容读出，并且理清楚文件架构
